version: '2'
services:
    notrans-mysql:
        container_name: notrans-mysql
        image: mysql:5.7.12
        # volumes:
        #     - ~/volumes/jhipster/notrans/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=notrans
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
